sudo: required

services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t harshilpadasala/docker-react .

script:
    - docker run -e CI=true harshilpadasala/docker-react npm run test
