version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run test
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app